/* Three-way causal video comparison with one lazily loaded case at a time. */
const causalSection=document.createElement('section');causalSection.id='causal';causalSection.className='section';
causalSection.innerHTML=`<div class="section-heading"><div><h2>Causal Video Generation</h2></div><p>Compare Causal Forcing, DMD†, and Ours on the same prompt with synchronized playback.</p></div><div id="causal-carousel" class="case-carousel" role="region" aria-roledescription="carousel" aria-label="Causal video case" data-carousel-group="causal"><div class="carousel-stage"><button class="carousel-arrow previous" data-causal-step="-1" aria-label="Previous causal video case" aria-controls="causal-results">‹</button><div id="causal-results" class="carousel-slide" tabindex="0" role="group" aria-roledescription="slide"></div><button class="carousel-arrow next" data-causal-step="1" aria-label="Next causal video case" aria-controls="causal-results">›</button></div><div class="carousel-footer"><span class="case-page" role="status" aria-live="polite" aria-atomic="true"></span></div></div>`;
document.querySelector('#video').after(causalSection);visibilityObserver.observe(causalSection);
available.causal=window.SMD_CAUSAL_CASES;state.causal=available.causal[0];resultIds.causal='causal-results';
renders.causal=function(){const c=state.causal;$('#causal-results').innerHTML=`<div class="three-col video-group causal-video-grid" style="--causal-ratio:${c.width}/${c.height}">${vid(c.routes.causal,'Causal Forcing')}${vid(c.routes.dmd,'DMD†')}${vid(c.routes.ours,'Ours','ours')}</div><div class="playback-tools"><button class="sync-button" data-sync="causal-results">▶ Play together</button></div>${prompt(c)}`};
causalSection.querySelectorAll('[data-causal-step]').forEach(button=>button.onclick=()=>stepCase('causal',Number(button.dataset.causalStep)));
causalSection.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.target.closest('video,input,textarea,select,button,a,summary'))return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();stepCase('causal',event.key==='ArrowLeft'?-1:1)}});
const causalStage=causalSection.querySelector('.carousel-stage');let causalGesture=null;
causalStage.addEventListener('pointerdown',event=>{if(!event.isPrimary||event.button!==0||event.target.closest('[data-causal-step],[data-sync],.video-start,summary,a'))return;causalGesture={x:event.clientX,y:event.clientY,id:event.pointerId}});
causalStage.addEventListener('pointerup',event=>{if(!causalGesture||causalGesture.id!==event.pointerId)return;const dx=event.clientX-causalGesture.x,dy=event.clientY-causalGesture.y;causalGesture=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)stepCase('causal',dx<0?1:-1)});causalStage.addEventListener('pointercancel',()=>causalGesture=null);
changeCase('causal',available.causal[0].code);
